{"text": "Great food, used this place a few times in the past. Never had any issues getting a table, service is excellent.", "title": "Julian lloyd ", "date": "9 January 2020", "restaurant": " Grapes Tandoori Indian Restaurant "}
{"text": "Grapes special is perfect for 2 person, taste is amazing. Service & quality of food are fantastic, nice decor and clean environment.", "title": "Best in the Area ", "date": "17 September 2019", "restaurant": " Grapes Tandoori Indian Restaurant "}
{"text": "I am not usually a fan of tapas restaurants as I generally find you end up spending too much and go away still hungry. However, Dar give very generous portions, that are great for either sharing or having yourself. Our group of 4 chose 4 lights portions to share initially, then a single dish (from the second page) to have individually afterwards. All of our different choices were delicious and we finished off with the baklava and fruit plates and a \u2018tomato\u2019 with coffees. The cost was very acceptable and we were all very satisfied. Very happy to recommend.", "title": "Much better than expected!", "date": "30 November 2019", "restaurant": " Mezzet Dar "}
{"text": "Good for cocktails & little snacks , friendly atmosphere, bit expensive, but good for quick snacks & cocktails ", "title": "Good", "date": "6 October 2019", "restaurant": " Mezzet Dar "}
{"text": "Amazing food , friendly staff. Defo one of the best Italians around!! I\u2019m going to come back with my Friends again", "title": "Fantastic place", "date": "24 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "Was here yesterday10th September with my husband and three friends for lunch.", "title": "Lunchtime Heaven", "date": "10 September 2019", "restaurant": " Sweet Rose Cakery "}
{"text": "On a busy Friday evening, the staff were happy to arrange my choice of meal which wasn't on the menu. We sat at the front of the restaurant in the bar area & it was very comfortable. Nice, lively atmosphere in the place.Highly recommended!", "title": "Excellent Food & Service", "date": "26 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "Tasty and homemade food inside a calm and cozy atmosphere. We were served by Jonas who suggested some nice entries and mains, always with a friendly smile and very helpful. Good portions sizes with a lovely dessert in the end. We definitely coming back.", "title": "Anniversary", "date": "1 February 2020", "restaurant": " Mezzet Lebanese Restaurant "}
{"text": "Visited on Saturday 5th with family and friends what a wonderful afternoon tea - in fact my very first one ! Staff so friendly and obliging, nothing too much trouble. Good variety of sandwiches and so fresh; cupcakes delicious and beautiful - hot - scones with a generous helping of cream and jam. D\u00e9cor so quaint and pretty. Will definitely be going back :-)", "title": "WONDERFUL AFTERNOON TEA", "date": "7 October 2019", "restaurant": " Sweet Rose Cakery "}
{"text": "Once again my favourite restaurant doesn\u2019t disappoint. Fantastic service, even better food. Big shout out to Jonas,l and the restaurant is looking great at Christmas. Thank you. ", "title": "Once again my favourite restaurant", "date": "23 December 2019", "restaurant": " Mezzet Lebanese Restaurant "}
{"text": "Honestly i am astonished by the service and food delivered by the staff and the atmosphere of the restaurant is always positive,I would highly recommend .", "title": "phenomenal", "date": "17 September 2019", "restaurant": " Grapes Tandoori Indian Restaurant "}
{"text": "The staff were very friendly and attending, the food was very exotic and definitely worth every penny. I would recommend this restaurant highly!!", "title": "Excellent Service!", "date": "24 January 2019", "restaurant": " Grapes Tandoori Indian Restaurant "}
{"text": "I have visited Ponte Nuovo many times and every time i visit i receive the same outstanding service and the same amazing food! Every single dish is fresh and tasty no matter what i have ordered. The pastas are an absolute MUST here, i am the biggest fan of the arrabbiata dish that is cooked to perfection, its a winner every time! The staff are always warm and welcoming which besides the amazing food is the reason i will always come back! Would recommend HIGHLY!", "title": "THE BEST!! Italian restaurant i have ever been too!", "date": "16 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "I\u2019ve been here more than 10 times now and they never fair to amaze me , the food is amazing at an excellent price , the staff is so professional and friendly , the restaurant as a whole is just a 10/10 , would 100% recommend", "title": "Excellent", "date": "16 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "Typically Italian food and actual Italian waiters. Eight of us had a great evening for my birthday. The service was prompt friendly. There is a good selection of wines and the prices are reasonable.", "title": "Great food and perfect service", "date": "17 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "For my mum's birthday we went for a 'luxury afternoon tea' at the west rose cakery. I booked the luxury one bacuase if came with smoked salmon sandwiches, which is my mum's favourite. She loved it. As we left she said 'I think that's the best afternoon tea I've had.' ", "title": "Mums birthday", "date": "29 August 2019", "restaurant": " Sweet Rose Cakery "}
{"text": "By far my favourite restaurant in Molesey. The food is amazing - I especially Love the calamari and prawn dishes. The service is professional and friendly. It is also great value for money! Can\u2019t waot to return :)", "title": "Top quality", "date": "14 December 2019", "restaurant": " Mezzet Lebanese Restaurant "}
{"text": "Brilliant food. Fabulous service. We had lunch here with our 2 year old. We had kibbeh, shared veggie platter and halloumi spring rolls. All top class. Will definitely go again", "title": "Brilliant food. Fabulous service.", "date": "15 December 2019", "restaurant": " Mezzet Lebanese Restaurant "}
{"text": "Excellent fodd, excellen service, excellent atmosphere. We tought to have a light dinner turned out to be the finest so far. The Chef is funny and experienced, stuff are elegant and well trained. The steak was perfect the wine was well suggested. Good example what you can bring out of a place if you love what you are doing.... ", "title": "There is nothing impssible.... ", "date": "4 January 2020", "restaurant": " La Plata Steakhouse "}
{"text": "Great food for a great price would recommend to anyone who wants amazing food the service is also very good, food came very quickly", "title": "Harry", "date": "31 December 2019", "restaurant": " La Plata Steakhouse "}
{"text": "I visited Jaipur of Chigwell, 3 nights in a row. I was on business staying at the Hallmark Hotel in Chigwell and have previously been to this Restaurant and was pleased with the food then. I can highly recommend the Sizzling Sali Chicken (Naga), Jaipur Garlic Chilli Chicken and Chicken with Chana Masala. All 3 dishes were very tasty. ", "title": "I visited Jaipur of Chigwell,", "date": "7 January 2020", "restaurant": " Jaipur of Chigwell "}
{"text": "Fantastic evening with outstanding food and service.", "title": "Outstanding food and service", "date": "12 November 2019", "restaurant": " Q Verde "}
{"text": "Second time coming here with the family all the way from South London. Great environment, lovely and attentive staff especially Delawar, such a lovely friendly gentleman.", "title": "Good food", "date": "1 February 2020", "restaurant": " Sahara Grill Hounslow "}
{"text": "It\u2019s a lovely restaurant but I\u2019m sorry I was disappointed with the Tandoori mixed grill. The chicken breast was small and the lamb shish wasn\u2019t much either. Other dishes were fine. Bit of a faff trying to split the bull. Would go again though.", "title": "Nice restaurant but a little disappointed ", "date": "30 October 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "Went to the restaurant at 6pm before the Kew Lights, there was free parking nearby/outside and they were fantastic at helping us (family of 6 with a new born) the service was quick and great.. they made us feel so welcome. The specials were nice and pasta Lovely! We will definitely be going back soon!", "title": "Amazing Genuine Italian", "date": "30 November 2019", "restaurant": " Q Verde "}
{"text": "My husband and I came here with family. We had been before and knew the food would be good. We weren't disappointed. The food was nice and served in a timely manner. The waitresses were attentive but not annoying. My cousin had the rabbit and said it was delicious. If you want good food, good service, at a good price, head here!!", "title": "Great food, fantastic service!", "date": "28 December 2019", "restaurant": " Ponte Nuovo "}
{"text": "Went here for my sister\u2019s birthday and couldn\u2019t fault it. The service was great and the portion size of the afternoon tea was more than enough (we all took something home). A large glass of Prosecco and unlimited tea came with it and all the sandwiches and cakes were fresh. It\u2019s a cost little place so you should book beforehand. ", "title": "Best Afternoon Tea! ", "date": "31 March 2019", "restaurant": " Sweet Rose Cakery "}
{"text": "Sometimes in life you need something reassuringly good and familiar. Ponte Nuovo succeeds in delivering reassurance and good quality in equal measure. The authentic touches are all there, along with a stylish flourish. A delight, long may it thrive. ", "title": "Reassuringly Good ", "date": "29 December 2019", "restaurant": " Ponte Nuovo "}
{"text": "Early dinner with friends (six of us in total). We decided upon one of the set menus for ease, which was really good value. The starters were particularly delicious and there were lots of them. Both the chicken and lamb main dishes were very good. With the help of the friendly staff we chose some very good Lebanese wines that were reasonably priced. Overall a lovely early evening dinner. Will certainly return.", "title": "Great Lebanese in East Molesey", "date": "2 December 2019", "restaurant": " Mezzet Lebanese Restaurant "}
{"text": "Fantastic food, fantastic service! We had a seafood spaghetti and a rib eye steak, the food was cooked to perfection, the staff were attentive without being intrusive. I cannot recommend this restaurant enough! We will be back...", "title": "Amazing!", "date": "2 January 2020", "restaurant": " Ponte Nuovo "}
{"text": "We went there with my girl friend to have -a muscle food right after weightlifting. Waiting staff was welcoming and the place was packed on a Thursday lunch. We shown to sit by the window. I wanted to have their lunch offer \u00a310 Steak and Fries but their Patron was taking our orders and asked us if we wanted mashed sweet potatoes!instead fries with our Steaks that was a dream workout meal. Kitchen team also sent us some little grilled bread while waiting our food. Steaks cooked to perfection! My friend and i really enjoyed. We are definitely going back there to ask the same dish tomorrow!", "title": "the best protein! Steaks cooked to perfection", "date": "14 December 2019", "restaurant": " La Plata Steakhouse "}
{"text": "I often pop in here for steak and chips. It's a nice little spot...the steaks are very good and the staff are great as well. Good choice of wines to go with the grub. Highly recommended and prices are not silly!", "title": "Lovely steaks!", "date": "14 December 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Best steaks in eastsheen. Juicy and delicious. We visit together with my wife. Eat best quality cuts of argentinien beef", "title": "Best steaks in eastsheen.", "date": "15 December 2019", "restaurant": " La Plata Steakhouse "}
{"text": "A very extensive menu. Dishes are rich and spicy and full of flavour. Smooth friendly service and very good value for London.", "title": "Best curry I've had for ages!", "date": "4 September 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "Our regular Indian restaurant closed so we thought we would try here......really lovely....can\u2019t recommend enough.", "title": "Top take away", "date": "6 September 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "Best curry I\u2019ve had for long time and very good service. We really enjoyed our visit To Jaipur of Chigwell.We felt welcomed and beautiful service.Highly recorded. Thank you Jaipur.", "title": "Best Indian restaurant in Essex ", "date": "18 September 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "My wife & I booked for early dinner (18.30) at QVerde after a day visiting Kew Gardens. Found the restaurant online as my wife loves Italian food, but as always when booking \"blind\" not sure what to expect. Needn't have worried - it was a really great meal. One of the best Italian meals we've had in a long time! Location is good for Kew Gardens (5min slow walk from Kew Gardens station) and the welcome/service is very friendly. The food was excellent and the House Red was a good quality \"House\" wine. Be aware however, it's not \"cheap\" and it is clearly specified on the menu that they add 12.5% service to the bill (\"discretionary\"). Still think it was worth every penny, and would highly recommend.", "title": "A little Gem in Kew", "date": "20 September 2019", "restaurant": " Q Verde "}
{"text": "Vast menu choice and it took ages to decide on what to eat. Good portions and very tasty with lots of flavours. Excellent customer service. Waiter was very good in helping us choose dishes. Very reasonably priced. Signed up to their loyalty scheme which gives you discounts on food. Will be coming back. ", "title": "Birthday dinner", "date": "11 September 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "Place has a general feel of being just a little tired. Toilets are poor. But let\u2019s get to the food , popadums were oily and not properly cooked. Pickles were average at best and amounted to 3 bowls of tasteless green, red something but little mint or chilli so hard to say what they were. Cheap mango chutney and an onion mixed with a chilli jam perhaps?", "title": "Good and bad", "date": "15 September 2019", "restaurant": " Jaipur of Chigwell "}
{"text": "We must have been here 20 times since we live in Kew. It is a busy but friendly local restaurant with good food and decent wine and a free grappa/limoncello with the bill. One of best things is the mixed starter for all. Not cheap but a talking point and an ice-breaker. I love the liver with sage, my girls love the pasta. We all enjoy the evening (or lunch). I don't really have any negatives other than it can be draughty at the table by the door (avoid in winter). Best table is the round table in far corner as you come in if you a large group.", "title": "Very relaxed local with good food and wine and friendly service", "date": "28 September 2019", "restaurant": " Q Verde "}
{"text": "From the warm welcome to the complementary limoncellos at the end this was fantastic evening. Food was superb and service was excellent, friendly and attentive but not over the top.", "title": "Fantastic Meal", "date": "1 October 2019", "restaurant": " Q Verde "}
{"text": "Attentive and lovely staff. Tasty food. Lovely atmosphere. Particular thanks to the manager who gave us two lemoncello shots to wish me a happy birthday. I recommend the Vitello Milano. ", "title": "Tasty birthday meal. ", "date": "1 October 2019", "restaurant": " Q Verde "}
{"text": "Going to an event at Kew and wanted to find somewhere to have tea nearby, read reviews and opted to give it a whirl. It was one of those evenings when I did fancy Pizza, but, that is not on the menu, nevertheless we both had starters and main course along with a few drinks, the calamari was fab as was the artichoke starter, the scallops were lovely, the early evening was finished off with an irish coffee and then some limoncello's whilst the gent at the bar sang along to the music, all very nice.", "title": "Lovely", "date": "20 October 2019", "restaurant": " Q Verde "}
{"text": "Having visited Kew Gardens for a Friday evening exhibition, members of our party of six expressed a desire to grab something to eat. A quick internet search showed up Q Verde a short walk away; a quick phone call and a promise to arrange a table for 6, a short stroll and we were there. And were we glad to be! A truly excellent restaurant with great atmosphere, really friendly and helpful staff and food that was out of this World", "title": "last minute booking came up trumps", "date": "19 October 2019", "restaurant": " Q Verde "}
{"text": "We wanted somewhere close to Kew Gardens for supper, before going to the Chihuly Nights Exhibition, and were attracted to this restaurant by the excellent reviews, and it's proximity to our B & B in the same road. We passed it on our way there, and asked if we could have a table at 6, when they officially opened, and they says they were fully booked, but if we didn't mind being squeezed in a sort of cubby hole by the fuse boxes, they could fit us in, and we said \"fine\".", "title": "\"Practically Perfect in Every Way\"", "date": "21 October 2019", "restaurant": " Q Verde "}
{"text": "i have been there many times never dissapointed with their steaks! Lunch offer is a great value , food comes super fast on hot plates! Chimmichurri s yummy.", "title": "Never disappointed", "date": "14 November 2019", "restaurant": " La Plata Steakhouse "}
{"text": "My wife, daughter her boyfriend and I dinned here on Saturday night while visiting by daughter in Richmond. It a small restaurant not a big chain so really friendly.", "title": "A nice surprise and very reasonable for London", "date": "17 November 2019", "restaurant": " La Plata Steakhouse "}
{"text": "The food was lovely and the environment was beautiful. ", "title": "Superb first visit", "date": "16 December 2019", "restaurant": " ASK Italian "}
{"text": "Visited this wonderful littke restaurant after a visit to Kew Gardens . The food was amazing as was the welcome and the atmosphere. Will definitely return when we visit Kew again ", "title": "Fabulous food wonderful atmosphere", "date": "19 August 2019", "restaurant": " Q Verde "}
{"text": "Excellent food, flawlessly prepared. The restaurant was cheeful and attractive. The waitstaff were friendly and attentive. We would definitely go back.", "title": "a good find", "date": "25 August 2019", "restaurant": " Q Verde "}
{"text": "Excellent food, great service. Would definitely recommend but one must book. I saw plenty of people chancing a table and being turned away. ", "title": "Italian gem ", "date": "30 August 2019", "restaurant": " Q Verde "}
{"text": "Food was OK; nothing special but nothing to complain about either. However the entire meal was mired by the behaviour of the owner. He told his colleague to send home one waitress half way through our meal and had the other one near to tears. We ate as quickly as we could and left; no longer prepared to witness such intimidation. Basil's cousin is alive and well and operating in Kew!", "title": "Fawlty Towers", "date": "30 August 2019", "restaurant": " Q Verde "}
{"text": "A family run friendly restaurant with a great atmosphere. We were met with a warm welcoming smile a the place had a real buzz about One slight downside was that we were shown to a table that hadn\u2019t been set and after some time we had to ask. OK a bit picky and no biggy, just a little irritating.Having said that the service was excellent and very friendly. The menu whilst not extensive had a good balanced choice. The star of the evening was the food which was excellent from starter to dessert. Overall well worth a visit.", "title": "Saturday Evening Dinner", "date": "2 September 2019", "restaurant": " Q Verde "}
{"text": "We had been to an evening event at Kew Gardens on Saturday night & problems with the District Line meant we knew we would be late getting back to our hotel in central London, so we decided to eat locally. ", "title": "Perfect supper ", "date": "15 September 2019", "restaurant": " Q Verde "}
{"text": "We had reserved a table for a name's day celebrations. We arrived happy and excited and on time with one bouquet of flowers and our table was half ready(missing half of the glasses, napkins, menus etc.) we asked if we can please put flowers in a vase and the waiter/owner said we have nothing and then we asked again and he gave a dry wine bucket stand and we asked to put some water if possible, he was grumpy about it. Also, we were left sitting at half ready table with our coats on, even though they were asking all the other guests if they want theirs taken to be hanged. That was a red flag, then we ordered some food and my sister glanced at the waiter and he straight away asked, with an attitude, what are you looking at?. At this point we starting to feel it might have been a mistake to come here. Long story short - We had 3 waiters change, orders were mixed up or forgotten, we had to chase them almost every time as they wouldn't stop at our table. Food - veal liver was under cooked and extremely greasy, mussels had actual rocks in them and they said it's ok don't worry, we wash them, when i complained about it twice... they didn't offer nothing even though i was clearly dissatisfied. Mains were decent but it was just pasta and desert was store bought and not cooked on the spot so was ok. Owner was walking and asked how everyone is except us for some reason? Maybe he needs to see you twice to show Italian hospitality? Before we were leaving he finally asked is all good and gave limoncello. The bill was not readable and seemed more than we expected around \u00a3150 for 3 adults 1 kid. One of the worst restaurant experiences ever, for that money we could've went to The Glasshouse (Michelin restaurant at Kew station) and would have been treated like humans and not like we shouldn't be there. I really don't understand how they get their high score! Arrivederci to Never Again. It's a shame though..", "title": "Heard and read good things, but in the end, we couldn't be More Disappointed...", "date": "3 September 2019", "restaurant": " Q Verde "}
{"text": "Three for an early midweek dinner. ", "title": "Thank you dinner", "date": "16 September 2019", "restaurant": " Q Verde "}
{"text": "Visited my sister and her husband ,who are both disabled,and took them here for lunch. The staff were so helpful and kind..sorting out seating and finding a home for the wheelchair.. ", "title": "Excellent steak", "date": "19 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Amazing service, even better food, nothing to fault. Perfect cooked steaks, tasty side, good choice in wine and gin. We will be back", "title": "Perfect Meal", "date": "21 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": " Booked this restaurant via TripAdvisor on the Sunday after walking passed the night before and seeing no tables free.", "title": "Nice place ", "date": "16 September 2019", "restaurant": " Q Verde "}
{"text": "Enchanting little local Italian - warm and friendly welcome - absolutely yummy food - delicious wines and we had a wonderful time - we\u2019ll be back very soon \u2764\ufe0f", "title": "Delightful", "date": "1 December 2019", "restaurant": " Treviso Restaurant "}
{"text": "Got in before six , great service even better food . This place is busy , rightly so . Portions size perfect , food so good you want more", "title": "Pre theatre nosh", "date": "25 January 2020", "restaurant": " VyTA Covent Garden "}
{"text": "Not in mainstream Richmond or Kew but a hidden gem. Not a large menu but very interesting and the food was the main event. As it should be.", "title": "Really good food", "date": "23 July 2019", "restaurant": " Q Verde "}
{"text": "Great place with great vibe. True Italian experience. We had the artichokes to start with, and that dish is to die for. We will definitely come back. ", "title": "Well recommended ", "date": "25 July 2019", "restaurant": " Q Verde "}
{"text": "We have lived in Kew since 2005 and, until recently, had never visited this place. Bizarre really, as it\u2019s on our doorstep. Anyway, about a month ago, I saw a lot of recommendations for it on the Next Door app, so my husband and I decided to give it a try...and we love it.", "title": "Just lovely!", "date": "28 July 2019", "restaurant": " Q Verde "}
{"text": "Enjoyed a lovely family meal here. There were 4 of us with a baby and we were given a warm welcome. We shared some poppadoms and nan bread and had a main course each- korma, tikka masala, jalfrezi and sathkora . They were all very tasty and we enjoyed coconut rice and sag aloo as sides. We also had a bottle of red wine. The staff were very friendly and the food really good . We got complimentary Baileys and brandy after the meal.", "title": "Good value tasty meal", "date": "7 November 2019", "restaurant": " The Amber Fort "}
{"text": "I went there with family, amazing food, fast service and an excellent atmosphere. Great prices to match with all of that!", "title": "Amazing", "date": "16 December 2019", "restaurant": " The Amber Fort "}
{"text": "Have used this restaurant since it opened aroun 15 years ago best Indian around have all family get together here always accommodating food always good never had to complain.Takeaways always good and arrives on time. Pat", "title": "Excellent", "date": "26 December 2019", "restaurant": " The Amber Fort "}
{"text": "I have mixed feelings about this restaurant, I ate here with friends on their George Michael tribute night and it was brilliant! Great food great service great atmosphere. Came to the restaurant last night (Thursday 12th December) and left feeling quite disappointed, on arrival I needed to use the loo and as I got to the door a male staff member came out of the ladies loo and left the seat up. The restaurant was quite empty with just another couple in there so the atmosphere understandably wasn\u2019t quite the same. We ordered our drinks and were asked if we were ready to order in which we replied please can we have a few minutes, after being asked another two times we ordered our starters only, another three or times after that they were pressuring us to order our mains to which I replied can we order it about 9.10pm (the time was 8.40pm) as we wanted a rest. The waiter then said we close at 11pm so ordering just after 9pm would have given us plenty of time, but no they wouldn\u2019t allow this and another waiter came over and insisted on taking our order. The food was lovely. We had desert while the staff stood there starring at us making it obvious they wanted us out of the restaurant so they can close making us feel extremely uncomfortable. Then my friend needed the loo but couldn\u2019t get in there because a male member of staff was using the ladies loo again, I challenged them and said it\u2019s probably not the right thing that customers have to wait while the staff use the ladies loo and for some reason they found this funny. ", "title": "I have mixed feelings about", "date": "13 December 2019", "restaurant": " The Amber Fort "}
{"text": "Great food and service. They could not do enough for us highly recommended. Easy parking on road and we took doggie bags home with us plenty of delicious food at not a high price xxx", "title": "Amber fort beckenham", "date": "4 January 2020", "restaurant": " The Amber Fort "}
{"text": "So i have been meaning to leave a review for this place for ages!! This restaurant is just outstanding! Great greeting when arriving (every time!), The staff are really pleasant to deal with, The food is always so mouthwateringly juicy (exept the chips obviously :P) and the whole experience makes me return often. Martin the owner always gos out of his way to make the night even more special too, Thank you Martin!", "title": "Quality Service, Quality Food and Quality Atmosphere!!!", "date": "9 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "We absolutely loved that place, the steak is amazing !! The staff are super friendly and they know some very good wines too, especially Joe he can make your night fabolous!! ", "title": "Fantastic food!!", "date": "9 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "My friends and I visited for my birthday and we were spoiled by all the staff,especially the by the restaurant owner ( chef ). The service was excellent and the staff were very attentive. ", "title": "heaven for the steak lovers!", "date": "13 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "We were two couples on a weekday eve.", "title": "Half argentinian only", "date": "12 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Drove past many times and finally booked a table. ", "title": "Good on all counts", "date": "24 November 2019", "restaurant": " Treviso Restaurant "}
{"text": "Great dishes, pasta, mussels, scallops etc.... are excellent.", "title": "great italian restaurant", "date": "27 September 2019", "restaurant": " Treviso Restaurant "}
{"text": "I'm an Italian lady and I've visited my English friends last week. They brought me to Q Verde and notwithstanding my hesitancy in going to Italian restaurants abroad, I must admit that my experience in this restaurant has been super. It was as if I were at home tasting mediterranean cuisine.", "title": "Excellent experience", "date": "28 May 2019", "restaurant": " Q Verde "}
{"text": "A small family restaurant with a fantastic welcoming atmosphere and attentive staff who provide first class service. The food was simply superb, delicious and the portions generous. My son and I loved it so much that we ate on a Saturday and returned on the Sunday night for more. I cannot praise this restaurant enough and look forward to visiting again when I am next in London. They also made a great Gaelic coffee.", "title": "Thank you for a wonderful meal", "date": "27 May 2019", "restaurant": " Q Verde "}
{"text": "Real lovely Italian restaurant, nice touch with bread sticks on table ,when you arrive ", "title": "Book in advance ", "date": "1 June 2019", "restaurant": " Q Verde "}
{"text": "As of fasting (lent) i have different appetite as it is normally. My friend found a great place at shepherd Bush market station (MR falafel) ", "title": "Nice surprise", "date": "7 March 2019", "restaurant": " Mr Falafel "}
{"text": "Quite literally the best! I've travelled a lot and this is both delicious, more than your money's worth and lovely staff. It's busy, so expect to wait but I NEVER see the problem in waiting for freshly made DECENT vegan food! Would come all the time if I lived in London! ", "title": "Best Falafel Ever!", "date": "27 April 2019", "restaurant": " Mr Falafel "}
{"text": "Best curry house in all of the land :-) we love amber fort so much! Have been getting take away from there for years and never had a bad meal plus the portions are very generous. We always joke that we\u2019d never move out of the amber fort delivery zone. The restaurant is just as lovely! My personal favourite is rezala chicken.", "title": "Restaurant and take away", "date": "18 August 2019", "restaurant": " The Amber Fort "}
{"text": "We arranged to hold a celebration meal at the Amber Fort for 22 people on a Saturday evening.It was suggested we pre order a number of different curries,sides, rices and Nans rather than having 22 people ordering seperately.This proved to be a great idea,the food came up all together ,allowing everybody a taste of different curries and the chance to try other dishes they may never have tried before.", "title": "Catering for a large party.", "date": "19 August 2019", "restaurant": " The Amber Fort "}
{"text": "Since day 1 I absolutely loved this cosy place in Sheen. Staff is great, they are always so helpful and make us feel welcomed. ", "title": "Have in or to go", "date": "9 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "I absolutely love La Plata - probably eat here at least once a week and the steak is always amazing. I\u2019m somewhat fussy when it comes to steak but it\u2019s always perfectly cooked (rare for me) and has lots of flavour. Also love the empanadas - can\u2019t manage a dinner at La Plata without them. Staff are also amazing and can not recommend them and the food highly enough.", "title": "The most delicious steak in London", "date": "6 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Just getting home from a delicious perfectly cooked rib-eye steak with pepper corn sauce and a mixed salad. As I had ordered Patatas Bravas as nibbles, excellent but quite big for one person, I was offered the mixed salad instead of the French Fries I had originally ordered with the steak. I\u2019m already looking forward to next Sunday evening. Very friendly and knowledgeable service.", "title": "Delicious Steak", "date": "6 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "The food was just amazing and the manager was really helpful and willing to help us! Greatest place and manager ever!!!!!", "title": "Best restaurant in Richmond.", "date": "6 October 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Me and my girlfriend were greeted warmly by Shemsi and our order was taken swiftly. The food was great. The service was excellent and very welcoming! Definitely come again!", "title": "Excellent lunch", "date": "2 August 2019", "restaurant": " ASK Italian "}
{"text": "We just popped in on the off chance of getting a table and from the moment we walked in we had a wonderful experience our host Gerardo let us choose the couple of tables that were free and made us very welcome ( we almost felt part of the family)", "title": "Brilliant just simply brilliant ", "date": "22 May 2019", "restaurant": " Q Verde "}
{"text": "Food was amazing! Had a great time, great and quick service by the manager Shemsi. Will definitely come again.", "title": "Great Service!", "date": "13 August 2019", "restaurant": " ASK Italian "}
{"text": "Staying in Richmond for the first time it fell to me to choose somewhere to eat for the 4 of us. Treviso is small, not over embellished but like the owners very welcoming. Our food was freshly prepared and delicious with special mention for our calamari starters. You need to visit a restauarant like Treviso to remind yourself of the difference between fresh quality food and what is on offer from the high street chains.", "title": "Small and intimate family Italian restaurant", "date": "7 June 2019", "restaurant": " Treviso Restaurant "}
{"text": "Having walked past this restaurant hundreds of times, we decided to finally venture inside and see what the had to offer.", "title": "Great local Italian", "date": "28 May 2019", "restaurant": " Treviso Restaurant "}
{"text": "Seafood risotto had 2 prawns and a slither of white fish. I'd say that was a rip off for \u00a314. Windows dirty too.", "title": "Poor", "date": "22 May 2019", "restaurant": " Treviso Restaurant "}
{"text": "The service, food, and wine list were all excellent. We visit Richmond once or twice a year for rugby matches and have always had decent meals, Then we tried the Treviso and it surpassed all our previous restaurant experiences in Richmond, by a long chalk. Will be visiting again in August for sure.", "title": "The best restaurant we have visited in Richmond.", "date": "15 July 2019", "restaurant": " Treviso Restaurant "}
{"text": "Treviso is a beautiful, rustic treasure serving absolutely delicious food. The service is incredible, they are willing to go off menu to meet anyone\u2019s needs. Would highly recommend this restaurant. ", "title": "Best Italian in the Twickenham/Richmond area!", "date": "18 August 2019", "restaurant": " Treviso Restaurant "}
{"text": "Just had dinner tonight with my son, oh man everything was so tasty! Service was great, they managed to squeeze us in despite being really busy. I had the sardines, veal chop and mouse my son had the pasta, although he also smashed into my dishes which he agreed were very tasty. I can recommend without reservation! ", "title": "Utterly scrumptious ", "date": "24 August 2019", "restaurant": " Treviso Restaurant "}
{"text": "Went for dinner on a Saturday night and thoroughly enjoyed. Great atmosphere and very nice steak and will be definitely coming back", "title": "First time - would definitely come back", "date": "1 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "The restaurant has a casual and rustic furnished style and was appropriate for a Quick Evening Meal. The staff were pleasant and the steaks served were very good. It was not over priced and certainly preferable to dine at than a 'restaurant chain' round the corner in Upper Richmond Road.", "title": "Good Quick Evening Meal", "date": "11 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Was extremely impress how cozy this restaurant was. The manager greeted us and welcome us with a great attitude and positivism which made us feel almost like at home. Food wise I give surely a 5 star review, tasty and tender steak probably one of the best I have had. Will definitely come back soon and recommend to all meat lovers prime quality beef, a special thank you to Joe for the awesome experience we both had. \u263a\ufe0f", "title": "Top place\ud83d\udc4c", "date": "15 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "The service was pleasant and speedy and the food was just delicious!", "title": "Delicious meat", "date": "18 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "I being a couple of times before and this place keeps getting better! Great ambience with a great playlist with music from South America. The empanadas and the calamari were yummy! We went for the Argentinian Experience which 4 cuts of steak cooked to perfection. So tender that almost no need of a steak knife! Dessert we shared a creme br\u00fbl\u00e9e \u201cthe Argentinian way) with dolce de leche in the bottom! Delicious! Si si si La Plata! Gracias ", "title": "Sii La Plata", "date": "26 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "Let's be honest, when you go to a restaurant the purpose is to be satisfied either by quality or amount of food, right? Well it happened to me when I visited, one of the best in London price-quality wise. Congratulations.", "title": "Proper Argentinian steakhouse", "date": "29 September 2019", "restaurant": " La Plata Steakhouse "}
{"text": "We had a wonderful lunch both choosing dishes from the fresh pasta section. It was so yummy! The staff are friendly-Shemsi in particular was so kind and nothing was too much trouble for us or the babies!", "title": "Yummy lunch with friend and babies", "date": "2 August 2019", "restaurant": " ASK Italian "}
{"text": "3 of us had lunch at Q Verde before an international at Twickenham, on the recommendation of a regular diner. It is small but nicely presented and, it being rugby day, had a great atmosphere. The owner, Gerardo, oversees a slick operation. The hospitality is out of this world, and the food is presented very efficiently. ", "title": "Excellent Restaurant ", "date": "17 March 2019", "restaurant": " Q Verde "}
{"text": "Exceptional fresh food. The Italian authentic in London. ", "title": "Fantastic Sunday night dinner", "date": "3 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "Had their off menu items which were really good. Nice ambience. Price was reasonable including their wines. Good italian wine offerings. ", "title": "Very tasty and authentic at reasonable prices ", "date": "14 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "Lovely experience, a varied menu and good atmosphere. Catered for Gluten free options very well too. Top evening!", "title": "Beautiful restaurant and great food. ", "date": "23 February 2019", "restaurant": " Treviso Restaurant "}
{"text": "This is our regular Sunday evening out. Initially it\u2019s a bit chaotic but the food and the warmth of our hosts makes up for it as we leave well fed and happy.", "title": "Homely hospitality", "date": "20 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "This was a new restaurant for 2 of our threesome but it was a very good choice and we all really enjoyed it. ", "title": "lunch with old business friends, a very nice choice with excellent food.", "date": "22 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "There were seven of us including a 3 year old! The welcome could not have been better, the fuss made of the 'little one' was so 'Italian' it made you wonder if we had been magically flown there!", "title": "Family eating", "date": "25 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "Very relaxed but great food and friendly service. It\u2019s extremely busy so we were made to wait for our table but we chilled out at the bar and had a couple of drinks. Very keen to return!", "title": "Really impressed", "date": "23 March 2019", "restaurant": " Treviso Restaurant "}
{"text": "Really nice wrap and falafel at a good price. Medium is huge don\u2019t bother getting a large! Really friendly people. Would definitely recommend", "title": "Amazing!", "date": "23 August 2018", "restaurant": " Mr Falafel "}
{"text": "We've had quite a few falafel wraps on our journeys and this one is the best so far. The ingredients are fresh and the wraps are packed full. Very highly recommended. ", "title": "Best falafel wrap so far!", "date": "5 February 2018", "restaurant": " Mr Falafel "}
{"text": "All round excellent, top quality food, great atmosphere, great staff. We are definitely going back to try other dishes.", "title": "best steak&empanada!", "date": "4 May 2019", "restaurant": " La Plata Steakhouse "}
